- src/main/java/com/exalttech/trex/core/ConnectionManager.java
- src/main/java/com/exalttech/trex/ui/views/logs/ConsoleLogView.java
Fixed infinite memory consumption
> Memory leaks

- src/main/java/com/exalttech/trex/core/ConnectionManager.java
- src/main/java/com/exalttech/trex/ui/controllers/ConnectDialogController.java
Now all errors will not be masked under network issues.
> Improve connection process.

- src/main/java/com/cisco/trex/stl/gui/controllers/capture/AddRecordPojo.java
- src/main/java/com/cisco/trex/stl/gui/controllers/capture/AddRecorderController.java
- src/main/java/com/cisco/trex/stl/gui/controllers/capture/FilterController.java
- src/main/java/com/cisco/trex/stl/gui/controllers/capture/MonitorController.java
- src/main/java/com/cisco/trex/stl/gui/controllers/capture/PacketCaptureDashboardController.java
- src/main/java/com/cisco/trex/stl/gui/controllers/capture/RecordController.java
- src/main/java/com/cisco/trex/stl/gui/services/capture/PktCaptureService.java
- src/main/resources/fxml/pkt_capture/AddRecord.fxml
- src/main/resources/fxml/pkt_capture/Filter.fxml
- src/main/resources/fxml/pkt_capture/Monitor.fxml
> Add monitor filter feature

- src/main/java/com/cisco/trex/stl/gui/controllers/capture/MonitorController.java
- src/main/java/com/cisco/trex/stl/gui/controllers/capture/PacketCaptureDashboardController.java
- src/main/java/com/cisco/trex/stl/gui/controllers/capture/RecordController.java
- src/main/java/com/exalttech/trex/ui/controllers/ImportPcapWizardController.java
- src/main/java/com/exalttech/trex/ui/controllers/MainViewController.java
- src/main/java/com/exalttech/trex/ui/controllers/PacketBuilderHomeController.java
- src/main/java/com/exalttech/trex/ui/util/AlertUtils.java
- src/main/java/com/exalttech/trex/ui/views/importPcap/ImportedPacketTableView.java
Example of PCAP import error alert:
> Add pcap import error alert & unify alert constructing

- src/main/java/com/cisco/trex/stl/gui/controllers/capture/MonitorController.java
- src/main/java/com/cisco/trex/stl/gui/controllers/capture/PacketCaptureDashboardController.java
- src/main/java/com/cisco/trex/stl/gui/controllers/capture/RecordController.java
- src/main/java/com/cisco/trex/stl/gui/models/Recorder.java
- src/main/java/com/cisco/trex/stl/gui/services/capture/PktCaptureService.java
- src/main/resources/fxml/pkt_capture/Layout.fxml
- src/main/resources/fxml/pkt_capture/Record.fxml
Also missing BPF filter column was added:
> Add inactive cyclic type recorders

- src/main/java/com/cisco/trex/stl/gui/controllers/dashboard/DashboardController.java
- src/main/java/com/exalttech/trex/ui/dialog/DialogView.java
- src/main/java/com/exalttech/trex/ui/dialog/DialogWindow.java
- src/main/resources/fxml/dashboard/Dashboard.fxml
- src/main/resources/styles/mainStyle.css
> Add dashboard service mode warning

- src/main/java/com/cisco/trex/stl/gui/controllers/dashboard/DashboardController.java
- src/main/java/com/exalttech/trex/ui/PortsManager.java
- src/main/java/com/exalttech/trex/ui/views/statistics/StatsLoader.java
Total queue full clearing was fixed. Also got rid of port state polling from dashboard.
> Queue full fix

- src/main/java/com/exalttech/trex/core/ConnectionManager.java
> Check connection status before sending disconnect event

- src/main/java/com/exalttech/trex/ui/controllers/MainViewController.java
> Fix clearing ports on disconnect

- src/main/java/com/exalttech/trex/core/ConnectionManager.java
- src/main/java/com/exalttech/trex/ui/controllers/ConnectDialogController.java
- src/main/java/com/exalttech/trex/ui/models/datastore/Connection.java
- src/main/resources/fxml/ConnectDialog.fxml
> Add ability to set timeout and improve timeout logic

- src/main/java/com/exalttech/trex/core/ConnectionManager.java
- src/main/java/com/exalttech/trex/ui/controllers/MainViewController.java
- src/main/resources/fxml/ConnectDialog.fxml
Also default timeout value was reduced, for now it's 3 seconds.
> Disconnect warning dialog

- src/main/java/com/exalttech/trex/ui/controllers/MainViewController.java
@kisel, I've changed a bit proposed message:
1. Timeout is not the one reason, we can get disconnected on proper TRex shut down
2. Added small clarification: application **connection** settings
> Update error message

- src/main/java/com/exalttech/trex/ui/views/statistics/StatsTableGenerator.java
- src/main/java/com/exalttech/trex/ui/views/statistics/cells/StatisticConstantsKeys.java
* Fixed incorrect labels Rx bps L1/L2
* Fixed Tx bps L1 total was always equals zero.
> Dashboard display fixes

- src/test/java/com/exalttech/trex/ui/UITestsServices.java
* Error was caused by commit https://github.com/TestFX/TestFX/commit/afc1df1
> Fixed UITestsServices compilation error

- src/main/java/com/exalttech/trex/ui/controllers/MainViewController.java
- src/main/java/com/exalttech/trex/ui/controllers/TrafficProfileDialogController.java
- src/main/java/com/exalttech/trex/util/ProfileManager.java
* Fixed handling ESC and close button 
* Fixed display context menu glitches
* Fixed exception when using context menu
> UI bugfix 

- src/main/java/com/exalttech/trex/ui/controllers/MainViewController.java
- src/main/java/com/exalttech/trex/ui/dialog/DialogManager.java
- src/main/java/com/exalttech/trex/ui/dialog/DialogWindow.java
* Minor refactoring
* Fixed creating and initializing new window on each dialog show request
(except Dashboard and profile editor, this windows need more accurate and deep changings)
* Repaired close on disconnect feature
* Changed DialogManager
* If dialog is opened already, and user tries to show it, it will become focused
* All dialogs are adding and removing handlers to DialogManager now
> Fixed dialog windows behaviour

- src/main/java/com/cisco/trex/stl/gui/controllers/dashboard/ports/PortsController.java
- src/main/java/com/exalttech/trex/ui/PortsManager.java
- src/main/java/com/exalttech/trex/ui/controllers/MainViewController.java
- src/main/java/com/exalttech/trex/ui/controllers/ports/tabs/PortHardwareCounters.java
- src/main/java/com/exalttech/trex/ui/views/statistics/StatsTableGenerator.java
* Fixed dummy ports issues
* Fixed dashboard with dummy ports issues
* Removed unused code block
> Dummy interfaces support

- src/main/java/com/exalttech/trex/ui/controllers/MainViewController.java
- src/main/resources/styles/mainStyle.css
Used resetAppInProgress to check if we are alredy scheduled Platform.runLater -- reset application process
p.s. 
most of changes are indentation
> Double alert disconnect fix

- build.gradle
- Added javafx plugin 
- Added version expand (e.g. "version.properties" file to write version number into build properly)
- Added wpcap dlls into build
> Gradle build installer support

- src/main/java/com/exalttech/trex/ui/controllers/daemon/ConfigTreeItem.java
- src/main/java/com/exalttech/trex/ui/controllers/daemon/TRexDaemonDialogController.java
- fixed Heavy Plus Sign code and appearance under windows
> Fixed invalid path format in TRex start from Daemon

- README.md
update README with supported TRex versions
https://github.com/cisco-system-traffic-generator/trex-stateless-gui/issues/131#issuecomment-796503213
> update README with supported TRex versions
